"""
Derive the demo dataset from the REAL collector run, so the dashboard shows real data.

    python -m scripts.build_demo_fixture        (from vouch/backend)

Reads  docs/sample_output.json   - 96 rows the live collector c_mszq0z1x27brru3wab actually
                                   returned from Newegg's GPU category page.
Writes tests/fixtures/newegg_live.json - the five runs MOCK_MODE replays.

Why this exists
---------------
The demo has to be deterministic and offline: a live demo that depends on a competitor site
redesigning on cue is a demo that fails on stage. But the alternative we started with - invented
products on example.com - answers "what did the structured output go on to power?" with "nothing
real". This script closes that gap: every product name, price, shipping cost, rating and stock flag
below is a value the live collector returned, and only the *failure* is constructed.

What is real and what is constructed, stated exactly:

    baseline        100% real. The 96 rows as returned, normalised out of Scraper Studio's
                    {"value": ..., "currency": "USD"} money shape.
    run_degraded    real rows with `price` removed on 3 of every 4, standing in for the null-spike
                    a layout change produces. This is what TRIGGERS a heal.
    healed_good     real rows with a small uniform price drift, standing in for a correct heal
                    against a page whose prices moved slightly.
    healed_swapped  real rows with `price` and `shipping` EXCHANGED. This is the failure the
                    guardian exists to catch, and the numbers on both sides of the swap are real:
                    a $6,900.00 ZOTAC RTX 5090 whose shipping is $19.99 reprices to $19.99.

`original_price` is absent throughout because the live collector did not capture it - Newegg shows a
crossed-out price on only ~33% of tiles. VALUE_ORDER_INVERTED is therefore exercised against
tests/fixtures/sample_runs.json, which is labelled demo data, and not claimed against live data.
"""

from __future__ import annotations

import json
from pathlib import Path

_BACKEND = Path(__file__).resolve().parents[1]
SOURCE = _BACKEND.parent / "docs" / "sample_output.json"
TARGET = _BACKEND / "tests" / "fixtures" / "newegg_live.json"

# Every 4th row keeps its price; the rest go null. A 75% null rate is comfortably past the
# degradation gate's threshold, which is what makes the heal fire on a measured fact.
DEGRADED_KEEP_EVERY = 4

# A correct heal against a page whose prices drifted down slightly. Applied uniformly so the
# resulting reprice proposals are legible on screen rather than noisy.
GOOD_HEAL_DRIFT = 0.992


def _money(value: object) -> float | None:
    """Scraper Studio returns money as {"value": 299.99, "currency": "USD", "symbol": "$"}.

    Non-USD is refused rather than coerced: newegg.ca does not redirect to .com and serves a
    different catalogue in CAD, so treating those numbers as dollars would poison the price history.
    """
    if isinstance(value, dict):
        if value.get("currency") not in (None, "USD"):
            raise ValueError(f"refusing non-USD price: {value}")
        value = value.get("value")
    if value is None:
        return None
    return round(float(value), 2)


def load_real_rows() -> list[dict]:
    """Flatten the live payload into the flat shape the guardian profiles."""
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    rows: list[dict] = []
    for record in payload["rows"]:
        for card in record.get("graphics_cards", []):
            name = str(card.get("name", "")).strip()
            price = _money(card.get("price"))
            if not name or price is None:
                continue
            row = {
                "name": name,
                "price": price,
                "shipping": _money(card.get("shipping")) or 0.0,
                "in_stock": bool(card.get("in_stock")),
            }
            if card.get("rating") is not None:
                row["rating"] = float(card["rating"])
            rows.append(row)
    return rows


def build(rows: list[dict]) -> dict:
    degraded = []
    for i, row in enumerate(rows):
        copy = dict(row)
        if i % DEGRADED_KEEP_EVERY != 0:
            copy["price"] = None
        degraded.append(copy)

    good = [{**row, "price": round(row["price"] * GOOD_HEAL_DRIFT, 2)} for row in rows]

    # The swap is total, exactly as a real column swap would be: every row exchanges the two
    # fields. Rows whose real shipping is $0.00 therefore reprice to $0.00, and rows whose real
    # shipping is $19.99 reprice to $19.99. Both are caught; we do not cherry-pick the dramatic ones.
    swapped = [{**row, "price": row["shipping"], "shipping": row["price"]} for row in rows]

    return {
        "_comment": (
            "Generated by scripts/build_demo_fixture.py from docs/sample_output.json - the real "
            "96-row output of Scraper Studio collector c_mszq0z1x27brru3wab against Newegg's GPU "
            "category page. 'baseline' is that run verbatim. 'run_degraded', 'healed_good' and "
            "'healed_swapped' are constructed FROM it to replay a layout break offline and "
            "deterministically; the values on both sides of the swap are the collector's own. "
            "Regenerate with: python -m scripts.build_demo_fixture"
        ),
        "_source": {
            "collector_id": "c_mszq0z1x27brru3wab",
            "url": "https://www.newegg.com/GPUs-Video-Graphics-Cards/SubCategory/ID-48?PageSize=96",
            "real_rows": len(rows),
        },
        "baseline": rows,
        "run_degraded": degraded,
        "healed_good": good,
        "healed_swapped": swapped,
    }


def main() -> None:
    rows = load_real_rows()
    if not rows:
        raise SystemExit(f"no usable rows in {SOURCE}")

    data = build(rows)
    TARGET.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")

    shipped = [r for r in rows if r["shipping"]]
    prices = sorted(r["price"] for r in rows)
    print(f"source     {SOURCE.relative_to(_BACKEND.parent)}")
    print(f"target     {TARGET.relative_to(_BACKEND)}")
    print(f"real rows  {len(rows)}  (prices ${prices[0]:,.2f} - ${prices[-1]:,.2f})")
    print(f"           {len(shipped)} rows carry non-zero shipping - these are the sharpest swaps:")
    for row in sorted(shipped, key=lambda r: -r["price"])[:4]:
        print(f"             ${row['price']:>9,.2f} -> ${row['shipping']:<6,.2f}  {row['name'][:56]}")


if __name__ == "__main__":
    main()
